import { Aircraft } from '../types';

export const aircrafts: Array<Aircraft> = [
  // EgyptAir aircrafts data
  {
    id: '1',
    type: 'A320-200',
    registration: 'SU-GCB',
    model: 'A320-200',
    capacity: 180,
    owner: 'EgyptAir',
    airlineId: '1',
    isPrivate: false,
  },
  {
    id: '2',
    type: 'A330-200',
    registration: 'SU-GCI',
    model: 'A330-200',
    capacity: 300,
    owner: 'EgyptAir',
    airlineId: '1',
    isPrivate: false,
  },
  {
    id: '3',
    type: '737-800',
    registration: 'SU-GDA',
    model: '737-800',
    capacity: 170,
    owner: 'EgyptAir',
    airlineId: '1',
    isPrivate: false,
  },
  {
    id: '4',
    type: '777-300ER',
    registration: 'SU-GDL',
    model: '777-300ER',
    capacity: 346,
    owner: 'EgyptAir',
    airlineId: '1',
    isPrivate: false,
  },
  {
    id: '5',
    type: '787-9',
    registration: 'SU-GEA',
    model: '787-9',
    capacity: 309,
    owner: 'EgyptAir',
    airlineId: '1',
    isPrivate: false,
  },

  // British Airways aircrafts data
  {
    id: '6',
    type: 'A320-200',
    registration: 'G-EUUR',
    model: 'A320-200',
    capacity: 180,
    owner: 'British Airways',
    airlineId: '2',
    isPrivate: false,
  },
  {
    id: '7',
    type: 'A380-800',
    registration: 'G-XLEA',
    model: 'A380-800',
    capacity: 469,
    owner: 'British Airways',
    airlineId: '2',
    isPrivate: false,
  },
  {
    id: '8',
    type: '747-400',
    registration: 'G-CIVB',
    model: '747-400',
    capacity: 299,
    owner: 'British Airways',
    airlineId: '2',
    isPrivate: false,
  },
  {
    id: '9',
    type: '777-200',
    registration: 'G-VIIO',
    model: '777-200',
    capacity: 275,
    owner: 'British Airways',
    airlineId: '2',
    isPrivate: false,
  },
  {
    id: '10',
    type: '787-9',
    registration: 'G-ZBKA',
    model: '787-9',
    capacity: 216,
    owner: 'British Airways',
    airlineId: '2',
    isPrivate: false,
  },

  // Emirates aircrafts data
  {
    id: '11',
    type: 'A380-800',
    registration: 'A6-EON',
    model: 'A380-800',
    capacity: 517,
    owner: 'Emirates',
    airlineId: '3',
    isPrivate: false,
  },
  {
    id: '12',
    type: '777-300ER',
    registration: 'A6-EGO',
    model: '777-300ER',
    capacity: 354,
    owner: 'Emirates',
    airlineId: '3',
    isPrivate: false,
  },
  {
    id: '13',
    type: '777-200LR',
    registration: 'A6-EWF',
    model: '777-200LR',
    capacity: 302,
    owner: 'Emirates',
    airlineId: '3',
    isPrivate: false,
  },
  {
    id: '14',
    type: '777-300',
    registration: 'A6-EBR',
    model: '777-300',
    capacity: 354,
    owner: 'Emirates',
    airlineId: '3',
    isPrivate: false,
  },
  {
    id: '15',
    type: '777-200',
    registration: 'A6-EMW',
    model: '777-200',
    capacity: 302,
    owner: 'Emirates',
    airlineId: '3',
    isPrivate: false,
  },
  // Lufthansa aircrafts data
  {
    id: '16',
    type: 'A320-200',
    registration: 'D-AIWE',
    model: 'A320-200',
    capacity: 180,
    owner: 'Lufthansa',
    airlineId: '4',
    isPrivate: false,
  },
  {
    id: '17',
    type: 'A340-300',
    registration: 'D-AIGY',
    model: 'A340-300',
    capacity: 279,
    owner: 'Lufthansa',
    airlineId: '4',
    isPrivate: false,
  },
  {
    id: '18',
    type: '747-8',
    registration: 'D-ABYI',
    model: '747-8',
    capacity: 364,
    owner: 'Lufthansa',
    airlineId: '4',
    isPrivate: false,
  },
  {
    id: '19',
    type: '777-9',
    registration: 'D-ABYA',
    model: '777-9',
    capacity: 414,
    owner: 'Lufthansa',
    airlineId: '4',
    isPrivate: false,
  },
  {
    id: '20',
    type: '787-9',
    registration: 'D-ABYI',
    model: '787-9',
    capacity: 304,
    owner: 'Lufthansa',
    airlineId: '4',
    isPrivate: false,
  },
];
